# NumPy
* ```NumPy stands for Numerical Python```
* ``` It is the core library for numeric and scientific computing.```
   * ```It consists of a multi dimensional array objects ```
   * ```Collection of routines to process those arrays. ```
* ```Python provides the ability to work on these multidimensional arrays.```

# NumPy Arrays

### 1. SingleDimensional Array

In [1]:
# Creating a single dimensional array
# To do so first we have to import NumPy Library
import numpy as np

# Thus created a 1D Array
n1 = np.array([10, 20, 30, 40, 50])

# Printing the array in the output
n1

array([10, 20, 30, 40, 50])

### 2. Multi-Dimensional Array 

In [3]:
# Creating a Multi dimensional array
# To do so first we have to import NumPy Library
import numpy as np

# Thus created a multi dimensional array
n2 = np.array([[10, 20, 30, 40, 50], [40, 50, 60, 70, 80]])

# Printing the array in the output
n2

array([[10, 20, 30, 40, 50],
       [40, 50, 60, 70, 80]])

In [4]:
# Check the type of the n1
type(n1)

numpy.ndarray

In [5]:
# Check the type of the n2
type(n2)

numpy.ndarray

# Initializing NumPy arrays with Zeros
* ```Invoke zeros method with dot operator.```
* ```Syntax : np.zeros((5,5))```

In [8]:
import numpy as np

n3 = np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
type(n3)

numpy.ndarray

In [8]:
import numpy as np

n3 = np.zeros((5,5))
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Initializing NumPy arrays with Same number
* ```Invoke full method with dot operator.```
* ```Syntax : np.full((5,5),(10))```

In [11]:
import numpy as np
n4 = np.full((5, 5), (108))
n4

array([[108, 108, 108, 108, 108],
       [108, 108, 108, 108, 108],
       [108, 108, 108, 108, 108],
       [108, 108, 108, 108, 108],
       [108, 108, 108, 108, 108]])

# Initializing NumPy within a range 
* ``` Syntax : np.arange(10, 20) It prints the data from 10 to 19```
* ``` Syntax : np.arange(10, 50, 5) It prints the data in steps of 5.```

In [12]:
import numpy as np
n5 = np.arange(10, 30)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [13]:
import numpy as np
n6 = np.arange(10, 50, 5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45])

# Print random numbers 
* ``` Syntax : np.random.randint(10, 100, 6).```
* ``` This prints a random set of data from 10 to 100. Number of elements in a set would be 6.```

In [14]:
import numpy as np
n7 = np.random.randint(10, 100, 5)
n7

array([14, 15, 30, 25, 56])

# Change the shape of the array

In [15]:
import numpy as np
n8 = np.array([[1,2,3],[4,5,6]])
n8

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# Now there are 2 rows and 3 columns
# So the shape is (2,3)
n8.shape

(2, 3)

In [18]:
# Now we change it to (3,2)
n8.shape = (3,2)

In [19]:
n8

array([[1, 2],
       [3, 4],
       [5, 6]])

# Joining NumPy Arrays
* ``` 1. Vertical Stack  = vstack( )```
* ``` 2. Horizontal Stack = hstack( )```
* ``` 3. Column Stack = column_stack( )```

## 1. Vertical Stack
* ``` We import vstack using dot operator.```

In [28]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

In [29]:
np.vstack((n1, n2))

array([[10, 20, 30],
       [40, 50, 60]])

## 2. Horizontal Stack
* ``` We import hstack using dot operator. ```

In [30]:
np.hstack((n1, n2))

array([10, 20, 30, 40, 50, 60])

## Column Stack
* ``` We import column_stack using dot operator```

In [32]:
np.column_stack((n1, n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# NumPy  Intersection and Difference

## 1. To find the common elements in two 1D arrays we use a function called ``intersect1d(n1, n2)``

In [41]:
import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 80, 90, 100])
n2 = np.array([20, 30, 40, 50 , 60 , 70])

In [42]:
# Use intersect1d function
# It gives the common elements in both the arrays
np.intersect1d(n1, n2)

array([20, 30, 40, 50])

## 2. To get the elements of n1 only removing the lements of n2 we use a function called ```setdiff1d(n1, n2)```

In [43]:
np.setdiff1d(n1, n2)

array([ 10,  80,  90, 100])

In [44]:
np.setdiff1d(n2, n1)

array([60, 70])

# Sum of two NumPy Arrays

In [46]:
import numpy as np
n1 = np.array([10, 20, 30])
n2 = np.array([40, 50, 60])

np.sum([n1, n2])

210

## To set the axis values 
* ``` If axis value is set to zero then it adds up the vertical values of n1 nd n2.```
* ``` If axis value is set to one then it first adds up the horizontal values of n1 and secondly adds       up the horizontal values of n2 and the result would be [sum of n1,  sum of n2] ```
* ``` If axis value is set to 2 then it displays the error stating that it is out of bound. ```


In [47]:
np.sum([n1, n2], axis=0)

array([50, 70, 90])

In [48]:
np.sum([n1, n2], axis=1)

array([ 60, 150])

In [49]:
np.sum([n1, n2], axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

# NumPy Array Basic arithmetic operations

## 1. Adding all elements in the array 

In [50]:
n1

array([10, 20, 30])

In [51]:
n2

array([40, 50, 60])

In [53]:
n1 + 100

array([110, 120, 130])

In [54]:
n2 + 200

array([240, 250, 260])

## 2. Subtracting all elements in the array 

In [55]:
n1 - 1

array([ 9, 19, 29])

In [56]:
n2 - 1

array([39, 49, 59])

## 3. Multiplying all elements in the array 

In [57]:
n1 * 10

array([100, 200, 300])

In [58]:
n2 * 20

array([ 800, 1000, 1200])

## 4. Dividing all elements in the array 

In [59]:
n1 / 2

array([ 5., 10., 15.])

In [60]:
n2 / 3

array([13.33333333, 16.66666667, 20.        ])

# Some of the mathematical functions in NumPy 

## ``` 1. Mean```
## ```2. Median```
## ``` 3. Standard Deviation```

In [64]:
# Mean of the array n1

import numpy as np
n1 = np.array([10, 20, 30, 40, 50, 75])
np.mean(n1)

37.5

In [65]:
# Median of the array n1

np.median(n1)

35.0

In [67]:
# Standard deviation of the array n1

np.std(n1)

21.16404183200049

# NumPy SAVE and LOAD array data
* ``` Syntax for save is np.save('name_user_defined', n1) ```
* ``` Syntax for load is np.load('name_user_defined.npy')```

In [68]:
# To save the array data
import numpy as np
n1 = np.array([10, 20, 30, 40, 50])
np.save('numpy_array', n1)

In [69]:
# Now loading the NumPy array to a new array n2
n2 = np.load('numpy_array.npy')
n2

array([10, 20, 30, 40, 50])